[build]
  # This ensures the Node script runs AFTER the Angular build
  command = "ng build --configuration production && node replace-env.js"
  # Double check this matches your actual dist folder structure
  publish = "dist/ai-saas-testing-platform/browser"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
